version: "3"

services:
  mysql-db:
    env_file:
      - .env
    build:
      context: database_containers/mysql/
      dockerfile: Dockerfile
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hagr-shared-network
  postgres-db:
    env_file:
      - .env
    build:
      context: database_containers/postgres/
      dockerfile: Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hagr-shared-network
  app:
    env_file:
      - .env
    build:
      context: app/
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - hagr-shared-network
volumes:
  mysql_data:
  postgres_data:
networks:
  hagr-shared-network:
    driver: bridge
